parameters:
- name: RunOrtExtensionsTests
  # this is only nuget packing pipeline, we don't want to run test again for that
  # we should have run the test somewhere already.
  displayName: Run Tests?
  type: boolean
  default: false

- name: DoCompliance
  displayName: Run Compliance Tasks?
  type: boolean
  default: true

- name: DoEsrp
  displayName: Run code sign tasks? Must be true if you are doing an OnnxRuntime extensions release.
  type: boolean
  default: true

- name: IsReleaseBuild
  displayName: Is a release build? Set it to true if you are doing an OnnxRuntime extensions release.
  type: boolean
  default: false

trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "*"
      
stages:
- template: templates/build-package-for-nuget.yml
  parameters:
    RunOrtExtensionsTests: ${{ parameters.RunOrtExtensionsTests }}
    DoCompliance: ${{ parameters.DoCompliance }}
    DoEsrp: ${{ parameters.DoEsrp }}
    IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
    OrtNugetPackageId: 'Microsoft.ML.OnnxRuntime.Extensions'
